"""add organization fields to cs_cases

Revision ID: 2b2a0c522159
Revises: 97158b0ab9fe
Create Date: 2026-02-11 14:43:04.938977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2a0c522159'
down_revision: Union[str, Sequence[str], None] = '97158b0ab9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cs_cases', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('cs_cases', sa.Column('org_phone', sa.String(), nullable=True))
    op.add_column('cs_cases', sa.Column('org_contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cs_cases', 'org_contact')
    op.drop_column('cs_cases', 'org_phone')
    op.drop_column('cs_cases', 'organization')
    # ### end Alembic commands ###
