"""add quote_request_id to notifications

Revision ID: 6cb5bdee0f2e
Revises: 6cfaa0f02ad2
Create Date: 2026-02-12 18:05:52.982907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb5bdee0f2e'
down_revision: Union[str, Sequence[str], None] = '6cfaa0f02ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('quote_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'quote_requests', ['quote_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'quote_request_id')
    # ### end Alembic commands ###
