"""add quote_requests tables

Revision ID: 6cfaa0f02ad2
Revises: 2b2a0c522159
Create Date: 2026-02-12 17:42:39.797076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cfaa0f02ad2'
down_revision: Union[str, Sequence[str], None] = '2b2a0c522159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('quote_request', sa.Text(), nullable=False),
    sa.Column('other_request', sa.Text(), nullable=True),
    sa.Column('failed_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_request', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'DONE', name='quoterequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_requests_id'), 'quote_requests', ['id'], unique=False)
    op.create_table('quote_request_assignees',
    sa.Column('quote_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_request_id', 'user_id')
    )
    op.create_table('quote_request_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['quote_request_comments.id'], ),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_request_comments_id'), 'quote_request_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_request_comments_id'), table_name='quote_request_comments')
    op.drop_table('quote_request_comments')
    op.drop_table('quote_request_assignees')
    op.drop_index(op.f('ix_quote_requests_id'), table_name='quote_requests')
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
