"""add author_id to checklists

Revision ID: 97158b0ab9fe
Revises: a74d5cffc80d
Create Date: 2026-02-11 14:37:52.706546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97158b0ab9fe'
down_revision: Union[str, Sequence[str], None] = 'a74d5cffc80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'checklists', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklists', type_='foreignkey')
    op.drop_column('checklists', 'author_id')
    # ### end Alembic commands ###
