"""add is_quote_assignee to users

Revision ID: c6dea675742f
Revises: 6cb5bdee0f2e
Create Date: 2026-02-13 12:59:43.238408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6dea675742f'
down_revision: Union[str, Sequence[str], None] = '6cb5bdee0f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_quote_assignee', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_quote_assignee')
    # ### end Alembic commands ###
