"""add tag_master table

Revision ID: d3f3fe3ddc15
Revises: 37d794a31d8b
Create Date: 2026-02-09 14:18:56.813758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f3fe3ddc15'
down_revision: Union[str, Sequence[str], None] = '37d794a31d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('keyword_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_master_id'), 'tag_master', ['id'], unique=False)
    op.create_index(op.f('ix_tag_master_name'), 'tag_master', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_master_name'), table_name='tag_master')
    op.drop_index(op.f('ix_tag_master_id'), table_name='tag_master')
    op.drop_table('tag_master')
    # ### end Alembic commands ###
